wilg_django_site/userena/contrib/umessages/urls.py
from django.conf.urls.defaults import *
from userena.contrib.umessages import views as messages_views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^compose/$',
        messages_views.message_compose,
        name='userena_umessages_compose'),

    url(r'^compose/(?P<recipients>[\+\.\w]+)/$',
        messages_views.message_compose,
        name='userena_umessages_compose_to'),

    url(r'^reply/(?P<parent_id>[\d]+)/$',
        messages_views.message_compose,
        name='userena_umessages_reply'),

    url(r'^view/(?P<username>[\.\w]+)/$',
        login_required(messages_views.MessageDetailListView.as_view()),
        name='userena_umessages_detail'),

    url(r'^remove/$',
        messages_views.message_remove,
        name='userena_umessages_remove'),

    url(r'^unremove/$',
        messages_views.message_remove,
        {'undo': True},
        name='userena_umessages_unremove'),

    url(r'^$',
        login_required(messages_views.MessageListView.as_view()),
        name='userena_umessages_list'),
)

wilg_django_site/userena/urls.py
from django.conf.urls import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt',
        'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
        },
       name='userena_password_reset'),
    url(r'^password/reset/done$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w-]+)/signup/complete$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

wilg_django_site/wilg_django_site/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from wds.models import Member
from accounts.models import MyProfile
from django.db.models import Max
from django.contrib.auth.models import User, Permission
from django.views.generic.list import ListView
from userena.forms import SignupFormExtra

from afs import pts

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

def get_current_usernames():
    pts_query = pts.PTS(None, pts.PTS_UNAUTH)
    pts_result = pts_query.getEntry('system:wilg')
    names = [m._get_name() + "@mit.edu" for m in pts_result.members]
    return names

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wilg_django_site.views.home', name='home'),
    # url(r'^wilg_django_site/', include('wilg_django_site.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'wds.views.index', name='index'),
    url(r'^about', 'wds.views.about'),
    url(r'^rush', 'wds.views.rush'),
    url(r'^house', 'wds.views.house'),

    # omg django query syntax
    # get current member names
    url(r'^members', 
        ListView.as_view(queryset=MyProfile.objects.order_by('year')
                         .reverse().filter(
                user__email__in=get_current_usernames())
                         .order_by('-user__last_name'),
                         template_name="userena/profile_list.html"), 
        name='wds.views.members'), # this is a hack for active link highlighting...
    url(r'^_members', 'wds.views._members'),

    url(r'^alumnae', 'wds.views.alumnae'),
    url(r'^exec', 'wds.views._exec'),
    url(r'^events', 'wds.views.events'),
    url(r'^contact', 'wds.views.contact'),

    url(r'^current',  'mit.scripts_login'),
    url(r'^alumni',  'mit.scripts_login'),
    url(r'^resources', 'wds.views.resources'),
    url(r'^accounts/', include('userena.urls')),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^slideshow/', include('slideshow.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

wilg_django_site/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile
from countries.models import Country, UsState

import datetime
YEAR_CHOICES = []
for r in range(1974, (datetime.datetime.now().year+5)):
	    YEAR_CHOICES.append((r,r))

MAJOR_CHOICES = []
for r in range(1, 25):
	if r == 13 or r == 19:
		continue
	MAJOR_CHOICES.append((str(r),str(r)))
MAJOR_CHOICES.extend([('STS', 'STS'), ('WGS', 'WGS'), ('CMS', 'CMS')])
#		 ('ES', 'Energy Studies'), ('AADS', 'African & African Diaspora Studies'), ('AIS', 'Applied International Studies'), ('Astronomy', 'Astronomy'), ('MES', 'Middle Eastern Studies'), ('PP', 'Public Policy'), ('RES', 'Russian and Eurasian Studies'), ('TEH', 'Toxicology and Environmental Health')])

MINOR_CHOICES = [
	('AADS', 'African & African Diaspora Studies'),
	('AS', 'American Studies'),
	('AMS', 'Ancient & Medieval Studies'),
	('Anthro', 'Anthropology'),
	('AIS', 'Applied International Studies'),
	('AAS', 'Archaeology and Archaeological Science'),
	('ACT', 'Art, Culture and Technology'),
	('AADS', 'Asian & Asian Diaspora Studies'),
	('CMS', 'Comparative Media Studies'),
	('DE', 'Development Economics'),
	('Econ', 'Economics'),
	('ES', 'Energy Studies'),
	('Ethics', 'Ethics'),
	('French', 'French'),
	('German', 'German'),
	('Spanish', 'Spanish'),
	('Chinese', 'Chinese'),
	('Japanese', 'Japanese'),
	('ELS', 'ELS'),
	('Portuguese', 'Portuguese'),
	('OL', 'Other Language'),
	('SILC', 'Studies in International Literatures and Cultures'),
	('TOL', 'Theory of Languages'),
	('Hist', 'History'),
	('HAA', 'History of Architecture and Art'),
	('LALS', 'Latin American & Latino Studies'),
	('Ling', 'Linguistics'),
	('Lit', 'Literature'),
	('MES', 'Middle Eastern Studies'),
	('Music', 'Music'),
	('Phil', 'Philosophy'),
	('Polisci', 'Political Science'),
	('PP', 'Public Policy'),
	('Psych', 'Psychology'),
	('RS', 'Religious Studies'),
	('RES', 'Russian and Eurasian Studies'),
	('STS', 'Science, Technology, and Society'),
	('Theater', 'Theater Arts'),
	('TOS', 'Toxicology and Environmental Health'),
	('US', 'Urban Studies'),
	('WGS', "Women's and Gender Studies"),
	('Writing', 'Writing'),
	]

DEPT_CHOICES = [('BS', 'BS'), ('MS', 'MS'), ('MEng', 'MEng'), ('PhD', 'PhD'),
		('Exchange', 'Exchange')]

MODIFIER_CHOICES = (
	('1', '1'),
	('2', '2'),
	('3', '3'),
	('7', '7'),
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),
	('E', 'E'),
	('ENG', 'ENG'),
	('F', 'F'),
	('H', 'H'),
	('L', 'L'),
	('M', 'M'),
	('OE', 'OE'),
	('W', 'W'),
)

EXEC_CHOICES = (
	('pres', 'President'),
	('vp', 'Vice President'),
	('secretary', 'Secretary'),
	('hm', 'House Manager'),
	('foodstud', 'Food Steward'),
	('social', 'Social Chair'),
	('treasurer', 'Treasurer'),
	('memco', 'Membership Coordinator'),
	('mal', 'Member at Large'),
	('risk', 'Risk Manager'),
	('rush', 'Rush Chair'),
	)

SEMESTERS = (
	('sp', 'Spring'),
	('su', 'Summer'),
	('fa', 'Fall'),
	('iap', 'IAP'),
	)

def tuplify(x):
	return (x, x) 

def tuplify_list(l):
	return [tuplify(x) for x in l]

class Location(models.Model):
	city = models.CharField(max_length=100, null=True, blank=True)
	state = models.CharField(max_length=100, null=True, blank=True, choices=tuplify_list(UsState.objects.all().values_list('name', flat=True)))
	country = models.CharField(max_length=100, choices=tuplify_list(Country.objects.all().values_list('name', flat=True)))
	major_city = models.CharField(_('Major nearby city'), max_length=70, null=True, blank=True )
	current = models.BooleanField(_('Current location?'), default=False)
	hometown = models.BooleanField(_('Hometown?'), default=False)
	user = models.ForeignKey('MyProfile')

class Affiliation(models.Model):
	institution = models.CharField(max_length=80)
	role = models.CharField(max_length=80)
	start_date = models.DateField()
	end_date = models.DateField(null=True)
	user = models.ForeignKey('MyProfile')

class Major(models.Model):
	number = models.CharField(_('Course'), choices=MAJOR_CHOICES, max_length=15)
	modifier = models.CharField(max_length=5, choices=MODIFIER_CHOICES, null=True, blank=True) # ex. "3", "OE", "C"
	user = models.ForeignKey('MyProfile')
	degree = models.CharField(_('Degree'), choices=DEPT_CHOICES, null=True, blank=True, max_length=10)


class MinorConc(models.Model):
	area = models.CharField(_('Area'), choices=MINOR_CHOICES, max_length=40)
	minortype = models.CharField(_('Association'), choices=[('Minor', 'Minor'), ('Concentration', 'Concentration')], max_length=20)
	user = models.ForeignKey('MyProfile')

class ExecRole(models.Model):
	title = models.CharField(choices=EXEC_CHOICES, max_length=40)
	year = models.IntegerField(_('year'), max_length=4, choices=YEAR_CHOICES, default=datetime.datetime.now().year)
	semester = models.CharField(choices=SEMESTERS, max_length=40)
	user = models.ForeignKey('MyProfile')

class MyProfile(UserenaBaseProfile):
        user = models.OneToOneField(User,unique=True,
                                    verbose_name=_('user'),related_name='my_profile')
	year = models.IntegerField(_('year'), max_length=4, choices=YEAR_CHOICES, default=datetime.datetime.now().year)
        oww = models.ForeignKey('self', null=True, blank=True, related_name='old_wise_one', verbose_name=_('Old wise one'))
	blurb = models.CharField(max_length=500, null=True, blank=True, verbose_name=_('You can ask me about...'))
	school = models.CharField(max_length=500, default='MIT')

	def __unicode__(self):
		return self.user.first_name + ' ' +  self.user.last_name + ' (' + str(self.year) + ')'

	def get_ydos(self):
		return self._default_manager.all().filter(oww__user__username=self.user.username)

	def get_bs_set(self):
		qset = self.major_set.filter(degree="BS")
		if not qset:
			# if they didn't have any BS degrees, they were probably
			# a special case. return all (other) degrees
			return self.major_set.all()
		return qset

wilg_django_site/wds/models.py
from django.db import models

# Create your models here.

class Exec(models.Model):
    member_id=models.IntegerField(null=False, unique=True)
    position=models.CharField(max_length=1000)
    year=models.IntegerField(null=False, unique=False) # year position held
    semester=models.BooleanField() # 0 = fall, 1 = spring semester

class Member(models.Model):
    name=models.CharField(max_length=1000)
    year=models.IntegerField(null=False, unique=False)
    major1=models.CharField(max_length=1000)
    major2=models.CharField(max_length=1000)
    minor1=models.CharField(max_length=1000)
    minor2=models.CharField(max_length=1000)
    oww=models.IntegerField(null=False, unique=False) # member id
    ydo=models.CommaSeparatedIntegerField(max_length=10000) # member ids
    blurb=models.TextField()
    hometown=models.CharField(max_length=1000)
    photo=models.CharField(max_length=1000) # a url

class Course(models.Model):
    '''
    represents a guess: an unordered set of numbers
    '''
    number=models.CharField(max_length=1000)
    name=models.CharField(max_length=1000)

wilg_django_site/userena/contrib/umessages/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from userena.contrib.umessages.fields import CommaSeparatedUserField
from userena.contrib.umessages.models import Message, MessageRecipient

import datetime

class ComposeForm(forms.Form):
    to = CommaSeparatedUserField(label=_("To"))
    body = forms.CharField(label=_("Message"),
                           widget=forms.Textarea({'class': 'message'}),
                           required=True)

    def save(self, sender):
        """
        Save the message and send it out into the wide world.

        :param sender:
            The :class:`User` that sends the message.

        :param parent_msg:
            The :class:`Message` that preceded this message in the thread.

        :return: The saved :class:`Message`.

        """
        um_to_user_list = self.cleaned_data['to']
        body = self.cleaned_data['body']

        msg = Message.objects.send_message(sender,
                                           um_to_user_list,
                                           body)

        return msg

wilg_django_site/userena/templates/userena/activate_fail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<p>{% trans "Your account could not be activated. This could be because your activation link has aged." %}</p>
<p>{% trans "Please try signing up again or contact us if you think something went wrong." %}</p>
{% endblock %}

wilg_django_site/userena/templates/userena/activate_retry_success.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Account re-activation succeeded." %}{% endblock %}
{% block content_title %}<h2>{% trans "Account re-activation" %}</h2>{% endblock %}

{% block content %}
<p>{% blocktrans %}You requested a new activation of your account..{% endblocktrans %}</p>
<p>{% blocktrans %}You have been sent an e-mail with an activation link to the supplied email.{% endblocktrans %}</p>
<p>{% blocktrans %}We will store your signup information for {{ userena_activation_days }} days on our server. {% endblocktrans %}</p>
{% endblock %}

wilg_django_site/userena/templates/userena/base_userena.html
{% extends "content.html" %}

wilg_django_site/userena/templates/userena/disabled.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Disabled account" %}{% endblock %}

{% block main_content %}
<p>{% trans "Your account has not been activated or has been disabled." %}</p>
<p>{% trans "If you have not received an activation email, please contact the computer chairs: wilg-compchairs[at]mit." %}</p>
{% endblock %} 

wilg_django_site/userena/templates/userena/email_change_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email verification" %}{% endblock %}
{% block content_title %}<h2>{% trans 'Confirm your new email' %}</h2>{% endblock %}

{% block content %}
<p>{% blocktrans with viewed_user.userena_signup.email_unconfirmed as email %}You have received an email at {{ email }}.{% endblocktrans %}</p>
<p>{% blocktrans with viewed_user.username as username %}To associate this email address with your account ({{ username }}) click on the link provided in this email.{% endblocktrans %}</p>
{% endblock %}

wilg_django_site/userena/templates/userena/email_confirm_fail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email verification failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your email could not be verified..." %}</h2>{% endblock %}

{% block content %}
<p>{% trans "Your email could not be verified..." %}</p>
<p>{% trans "You could try changing it again in your account settings." %}</p>
{% endblock %}

wilg_django_site/userena/templates/userena/password_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password changed" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been changed" %}.</h2>{% endblock %}

{% block content %}
<p>{% trans "From now on you can use your new password to signin" %}.</p>
{% endblock %}

wilg_django_site/userena/templates/userena/password_reset_confirm_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Reset password" %}" />
</form>
{% endblock %}

wilg_django_site/userena/templates/userena/password_reset_done.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset email sent" %}{% endblock %}

{% block main_content %}
<p>{% trans "An e-mail has been sent to you which explains how to reset your password." %}</p>
{% endblock %}

wilg_django_site/userena/templates/userena/profile_detail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% blocktrans with profile.user.get_full_name as username %}{{ username }}{% endblocktrans %}{% endblock %}

{% block main_content %}
{% include 'userena/profile_nav.html' %}

    <div id="details">
      {% block profile_details %}
        <img class="mugshot" src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />
        <dl>
          {% block profile_definition_list %}
	    {% if profile.major_set.exists %}
              <dt>{% trans "Degrees" %}</dt>
	      {% for major in profile.major_set.all %} 
	      <dd>{{major.degree}}, {{major.number}}{% if major.modifier %}-{{major.modifier}} {% endif %}<dd/>
	      {% endfor %}
	    {% endif %}
	    {% if profile.minorconc_set.exists %}
	      {% for minor in profile.minorconc_set.all %} 
              <dt>{{ minor.minortype }}</dt>
	      <dd>{{ minor.get_area_display }}<dd/>
	      {% endfor %}
	    {% endif %}
	{% if profile.school != "MIT" %}
		<dt> School </dt>
		<dd>{{profile.school}}</dd>
		{% endif %}
	    {% if profile.execrole_set.exists %}
              <dt>Exec positions</dt>
	      {% for role in profile.execrole_set.all %} 
	      <dd>{{role.get_title_display}}: {{role.get_semester_display}} {{ role.year }}<dd/>
	      {% endfor %}
	    {% endif %}
	    {% if profile.location_set.exists %}
	      {% for loc in profile.location_set.all %} 
	      {% if loc.hometown %}<dt>Hometown</dt>
	      <dd>{{ loc.city }}{% if loc.state %}, {{loc.state}}{% endif%}{% if loc.country %}, {{loc.country|title }}{% endif %}<dd/>{% endif %}
	      {% endfor %}
	    {% endif %}
            {% if profile.oww %}
		<dt>{% trans "Old wise one" %}</dt>
		<dd><a href="{% url 'userena_profile_detail' profile.oww.user.username %}">{{ profile.oww.user.get_full_name }}</a><dd/>
            {% endif %}
            {% if profile.get_ydos %}
		<dt>{% trans "Young dumb ones" %}</dt>
	      {% for ydo in profile.get_ydos.all %} 
	      	<dd><a href="{% url 'userena_profile_detail' ydo.user.username %}">{{ ydo.user.get_full_name }}</a><dd/>
	      {% endfor %}
            {% endif %}

	{% if user.is_authenticated %}
            {% if profile.user.email and not hide_email %}
              <dt>{% trans "Email" %}</dt>
              <dd>{{ profile.user.email }}</dd>
            {% endif %}
            {% if profile.blurb %}
              <dt>{% trans "Ask me about..." %}</dt>
              <dd>{{ profile.blurb }}</dd>
            {% endif %}
	{% endif %}
          {% endblock %}
        </dl>
      {% endblock %}
    </div>
  </div>
{% endblock %}

wilg_django_site/userena/templates/userena/profile_list.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block main_content %}
{% include 'userena/profile_nav.html' %}
{% regroup object_list|dictsort:"user.last_name"|dictsort:"year" by year as member_list %}
{% for year in member_list reversed %}
<ul id="profile_list">
<span class="year_header">Class of {{ year.grouper }}</span><br/>
  {% for profile in year.list %}
  <a href="{% url 'userena_profile_detail' profile.user.username %}">
  <li>
    <img src="{{ profile.get_mugshot_url }}" /><br/><br/>
  {{ profile.user.first_name }} {{profile.user.last_name}}<br/>
  {% if profile.major_set.exists %}
    Course {% for major in profile.get_bs_set %}
        {{major.number}}{% if major.modifier %}-{{major.modifier}}{% endif %} 
        {% if not forloop.last %} & {% endif %} 
  {% endfor %}{% endif %}<br/>
  </li></a>
  {% endfor %}

</ul>
{% endfor %}
{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
    {% endif %}

    <span class="current">
      {% blocktrans with page_obj.number as page and page_obj.paginator.num_pages as num_pages %}
      Page {{ page }} of {{ num_pages }}
      {% endblocktrans %}
    </span>

    {% if page_obj.has_next %}
    <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
    {% endif %}
  </span>
</div>
{% endif %}
{% endblock %}

wilg_django_site/userena/templates/userena/profile_nav.html
{% load i18n %}
{% load url from future %}

  <ul id="box-nav">
    {% if user.is_authenticated %}<li><a href="{% url 'userena_profile_list'%}">{% trans 'All profiles' %}</a></li>{% else %}<li><a href="/members/">{% trans 'All profiles' %}</a></li>{% endif %}
    {% if user.is_authenticated %}
    <li><a href="{% url 'userena_profile_detail' user.username %}">{% trans 'My profile' %}</a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
    <li><a href="/resources">{% trans "Member resources" %}</a></li>
    {% endif %}
  </ul>

  <div id="searchbar">
    
  </div>
<br/><br/>

wilg_django_site/userena/templates/userena/signin_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Sign in" %}{% endblock %}

{% block main_content %}
<form action="" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Signin" %}</legend>
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.errors }}
    {% comment %} Displaying checkboxes differently {% endcomment %}
    {% if field.name == 'remember_me' %}
    <p class="checkbox">
    <label for="id_{{ field.name }}">{{ field }} {{ field.label }}</label>
    </p>
    {% else %}
    <p>
    {{ field.label_tag }}
    {{ field }}
    </p>
    {% endif %}
    {% endfor %}
  </fieldset>
  <input type="submit" value="{% trans "Signin" %}" />
  <p class="forgot-password"><a href="{% url 'userena_password_reset' %}" title="{% trans 'Forgot your password?' %}">{% trans "Forgot your password?" %}</a></p>
  {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
</form>
{% endblock %}

wilg_django_site/userena/templates/userena/signup_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Member Registration" %}{% endblock %}

{% block main_content %}
<div id="signupform">
<form action="" method="post">
  {% csrf_token %}
  <fieldset>
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.errors }}
    {% comment %} Displaying checkboxes differently {% endcomment %}
    {% if field.name == 'tos' %}
    <p class="checkbox">
    <label for="id_{{ field.name }}">{{ field }} {{ field.label }}</label>
    </p>
    {% else %}
    <p>
    {{ field.label_tag }} 
    {{ field }}
    </p>
    {% endif %}
    {% endfor %}
  </fieldset>
  <input type="submit" value="{% trans "Register"%}" />
</form>
</div>
{% endblock %}